export type BusinessCategory =
  | "online"
  | "main-street"
  | "service"
  | "food"
  | "side"
  | "family";

export type BusinessIdea = {
  name: string;
  category: BusinessCategory;
  offer: string;
  startupCost: string;
  incomePotential: string;
  firstCustomers: string;
  stageHint: string;
};

export const BUSINESS_CATEGORIES: { id: BusinessCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "online", label: "Online" },
  { id: "main-street", label: "Main Street" },
  { id: "service", label: "Service" },
  { id: "food", label: "Food & Hands" },
  { id: "side", label: "Side hustle → full-time" },
  { id: "family", label: "Family-run" },
];

export const BUSINESS_IDEAS: BusinessIdea[] = [
  // ============== ONLINE (16) ==============
  {
    name: "AI receptionist for trades",
    category: "online",
    offer: "24/7 answering + booking for plumbers & HVAC. $400/mo per shop.",
    startupCost: "Starts under $1,500",
    incomePotential: "$10k–$25k / mo",
    firstCustomers: "Drive-bys to 30 trade shops with a 1-page demo",
    stageHint: "Stage 2 builds your pitch.",
  },
  {
    name: "Fractional bookkeeping for med-spas",
    category: "online",
    offer: "Monthly books + tax-ready reports. $600–$1,200 per client.",
    startupCost: "Starts under $1,000",
    incomePotential: "$8k–$18k / mo",
    firstCustomers: "DM 50 med-spa owners on IG with a 90-day offer",
    stageHint: "Stage 7 gets your first 5 retainers.",
  },
  {
    name: "LinkedIn ghostwriting for execs",
    category: "online",
    offer: "8 posts/month + 1 newsletter. $2,500/mo per client.",
    startupCost: "Starts under $300",
    incomePotential: "$10k–$25k / mo",
    firstCustomers: "Cold-DM 40 founders with 3 sample posts in their voice",
    stageHint: "Stage 2 picks the niche.",
  },
  {
    name: "Faceless YouTube + course funnel",
    category: "online",
    offer: "Niche channel (finance, history, AI tools) + $99 course on the back.",
    startupCost: "Starts under $500",
    incomePotential: "$3k–$15k / mo (after 6 mo)",
    firstCustomers: "TikTok + Shorts cross-posts in your niche",
    stageHint: "Stage 6 writes your first 30 scripts.",
  },
  {
    name: "Done-with-you Shopify launches for makers",
    category: "online",
    offer: "2-week store sprint + 30 days of support. $3,500 per launch.",
    startupCost: "Starts under $500",
    incomePotential: "$7k–$14k / mo",
    firstCustomers: "Etsy sellers ready to own their store — DM 50 of them",
    stageHint: "Stage 5 builds your sample store.",
  },
  {
    name: "AI inbox cleanup for small businesses",
    category: "online",
    offer: "Done-for-you email triage + templates. $300/mo per client.",
    startupCost: "Starts under $200",
    incomePotential: "$3k–$9k / mo",
    firstCustomers: "Realtors, contractors, LinkedIn DMs",
    stageHint: "Stage 2 builds your offer.",
  },
  {
    name: "Notion + AI ops for small businesses",
    category: "online",
    offer: "Build them a single dashboard for jobs, customers, money. $2,500 setup.",
    startupCost: "Starts under $200",
    incomePotential: "$5k–$15k / mo",
    firstCustomers: "Contractors, gym owners, salon owners in your city",
    stageHint: "Stage 4 builds the delivery flow.",
  },
  {
    name: "Niche paid newsletter + sponsorships",
    category: "online",
    offer: "Weekly newsletter for a real niche. $10/mo subs + sponsor slots.",
    startupCost: "Starts under $200",
    incomePotential: "$2k–$12k / mo",
    firstCustomers: "Pick a niche you know. Post 2 free issues a week for 60 days.",
    stageHint: "Stage 2 picks the niche.",
  },
  {
    name: "Etsy shop: Cricut nursery signs",
    category: "online",
    offer: "Custom name signs for baby showers. $35–$85 each.",
    startupCost: "Starts under $600",
    incomePotential: "$1.5k–$5k / mo",
    firstCustomers: "Etsy traffic, IG reels, baby-shower hashtags",
    stageHint: "Stage 5 builds your shop.",
  },
  {
    name: "Done-for-you AI content for realtors",
    category: "online",
    offer: "Listings → reels, captions, emails. $700/mo per agent.",
    startupCost: "Starts under $400",
    incomePotential: "$7k–$15k / mo",
    firstCustomers: "Walk into one brokerage with a free sample for 3 agents",
    stageHint: "Stage 6 builds your sample reel.",
  },
  {
    name: "Whatnot live-resell shop",
    category: "online",
    offer: "Sell vintage/thrift hauls live, 4 nights a week. $20–$80 per item.",
    startupCost: "Starts under $1,000",
    incomePotential: "$2k–$10k / mo",
    firstCustomers: "Whatnot's own viewers — your first stream tonight",
    stageHint: "Stage 4 builds your weekly show flow.",
  },
  {
    name: "Online tutoring with AI tools",
    category: "online",
    offer: "1-on-1 SAT, math, or reading help. $90/hour, 10 students/week.",
    startupCost: "Starts under $200",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Parent Facebook groups + 3 local school counselors",
    stageHint: "Stage 2 builds the offer parents say yes to.",
  },
  {
    name: "Bookkeeping for barbershops",
    category: "online",
    offer: "Remote monthly books + payroll. $250/mo per shop.",
    startupCost: "Starts under $500",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "5 shops in your zip code, walk in, leave a card",
    stageHint: "Stage 7 gets your first 5 clients.",
  },
  {
    name: "Notion templates for contractors",
    category: "online",
    offer: "Job tracker + estimate pack. $49 one-time.",
    startupCost: "Starts under $100",
    incomePotential: "$1k–$4k / mo",
    firstCustomers: "Contractor Facebook groups, Gumroad, LinkedIn",
    stageHint: "Stage 2 picks who you sell to.",
  },
  {
    name: "Done-with-you AI lead-gen for trades",
    category: "online",
    offer: "We set up calls, you book jobs. $1,500/mo per trade business.",
    startupCost: "Starts under $1,000",
    incomePotential: "$8k–$20k / mo",
    firstCustomers: "Roofers, HVAC, fence builders — 20 cold calls/day for 30 days",
    stageHint: "Stage 6 writes your outbound.",
  },
  {
    name: "Faceless TikTok Shop affiliate brand",
    category: "online",
    offer: "Pick a niche, post 3 videos a day, earn 8–20% per sale.",
    startupCost: "Starts under $200",
    incomePotential: "$1k–$10k / mo",
    firstCustomers: "TikTok's algorithm — show up daily for 60 days",
    stageHint: "Stage 6 builds your first 30 videos.",
  },

  // ============== MAIN STREET (14) ==============
  {
    name: "Mobile car detailing",
    category: "main-street",
    offer: "Wash, wax, vacuum at the driveway. $75 a visit, 3/day.",
    startupCost: "Starts under $2,000",
    incomePotential: "$4k–$9k / mo",
    firstCustomers: "Neighbors, apartment complexes, FB groups",
    stageHint: "Stage 4 builds your service flow.",
  },
  {
    name: "Self-pour coffee kiosk in a co-work space",
    category: "main-street",
    offer: "Tap-and-pay coffee inside an office. Revenue share with the landlord.",
    startupCost: "Starts under $9,000",
    incomePotential: "$3k–$8k / mo per location",
    firstCustomers: "Walk into 10 co-work spaces with a revenue-split pitch",
    stageHint: "Stage 2 builds the landlord pitch.",
  },
  {
    name: "Vending machine route at scale",
    category: "main-street",
    offer: "8–12 machines in gyms, laundromats, body shops.",
    startupCost: "Starts under $9,000 (4 machines, scale from there)",
    incomePotential: "$4k–$12k / mo",
    firstCustomers: "Owner-operators who'll split revenue. Knock on doors.",
    stageHint: "Stage 7 maps your first route.",
  },
  {
    name: "Pressure washing for commercial buildings",
    category: "main-street",
    offer: "After-hours sidewalks + drive-thrus. $400–$1,200 per stop.",
    startupCost: "Starts under $3,500",
    incomePotential: "$8k–$18k / mo",
    firstCustomers: "Property managers — 30 emails + before/after photos",
    stageHint: "Stage 7 maps your first route.",
  },
  {
    name: "Pop-up nail bar inside salons",
    category: "main-street",
    offer: "Rent a chair Thurs–Sat. $40 sets, $25 fills.",
    startupCost: "Starts under $1,000",
    incomePotential: "$2.5k–$6k / mo",
    firstCustomers: "Salon walk-ins, IG before/after posts",
    stageHint: "Stage 1 gets your license right.",
  },
  {
    name: "Pop-up golf simulator trailer",
    category: "main-street",
    offer: "Rent the trailer to bars, breweries, parties. $400–$1,500 per event.",
    startupCost: "Starts under $9,500",
    incomePotential: "$5k–$15k / mo",
    firstCustomers: "10 breweries within 30 miles. One yes books your weekends.",
    stageHint: "Stage 6 builds your event flyer.",
  },
  {
    name: "Pop-up axe-throwing nights",
    category: "main-street",
    offer: "Bring the targets, run a 2-hour event. $25/person, parties of 10–30.",
    startupCost: "Starts under $4,000",
    incomePotential: "$3k–$10k / mo",
    firstCustomers: "Breweries, corporate team builds, birthday parties",
    stageHint: "Stage 5 builds your booking site.",
  },
  {
    name: "Hair braiding studio in a spare room",
    category: "main-street",
    offer: "Box braids, knotless, locs by appointment. $150–$400.",
    startupCost: "Starts under $800",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "IG portfolio, friends-of-friends, referrals",
    stageHint: "Stage 1 gets your permits right.",
  },
  {
    name: "Mobile pet grooming van",
    category: "main-street",
    offer: "Full groom at the driveway. $90–$150 per dog, 5/day.",
    startupCost: "Starts under $9,500 (used van + setup)",
    incomePotential: "$6k–$14k / mo",
    firstCustomers: "FB neighborhood groups + vet office bulletins",
    stageHint: "Stage 4 builds the daily route.",
  },
  {
    name: "Mobile boat & RV detailing",
    category: "main-street",
    offer: "On-site clean & wax. $300–$900 per job, marinas + storage lots.",
    startupCost: "Starts under $3,000",
    incomePotential: "$6k–$15k / mo",
    firstCustomers: "Marina office bulletin boards, RV storage owners",
    stageHint: "Stage 2 builds your tiered offer.",
  },
  {
    name: "Sober-curious bottle shop pop-up",
    category: "main-street",
    offer: "Non-alcoholic wines, beers, spirits at markets + tastings.",
    startupCost: "Starts under $8,000",
    incomePotential: "$2k–$9k / mo (event-based)",
    firstCustomers: "Farmer's markets, wellness studios, women's groups",
    stageHint: "Stage 5 builds your brand kit.",
  },
  {
    name: "Solar panel cleaning route",
    category: "main-street",
    offer: "Quarterly cleans. $150–$400 per home, 4 homes/day.",
    startupCost: "Starts under $2,500",
    incomePotential: "$5k–$12k / mo",
    firstCustomers: "Door-hangers in solar-heavy neighborhoods",
    stageHint: "Stage 7 builds the quarterly route.",
  },
  {
    name: "Microgreens for chefs & subscribers",
    category: "main-street",
    offer: "Weekly delivery to 6 restaurants + 30 home subs.",
    startupCost: "Starts under $4,000 (shelves + lights in a spare room)",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Knock on 10 farm-to-table kitchens with a free sample",
    stageHint: "Stage 4 builds the weekly flow.",
  },
  {
    name: "Pickleball lessons & beginner clinics",
    category: "main-street",
    offer: "Group clinics at public courts. $40/person, 8 players/clinic.",
    startupCost: "Starts under $1,500",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Parks & Rec partnerships + 2 IG posts a week",
    stageHint: "Stage 2 builds the clinic packages.",
  },

  // ============== SERVICE (14) ==============
  {
    name: "Junk hauling with a second truck",
    category: "service",
    offer: "Garage + estate cleanouts. $200–$800 per job, 4–6/day.",
    startupCost: "Starts under $9,000 (used truck + dump trailer)",
    incomePotential: "$10k–$25k / mo",
    firstCustomers: "Thumbtack, Facebook Marketplace, realtors",
    stageHint: "Stage 6 builds your ad creatives.",
  },
  {
    name: "Mobile auto-glass replacement",
    category: "service",
    offer: "On-site windshield replace. $250–$500 per job, 3/day.",
    startupCost: "Starts under $7,500 (training + tools)",
    incomePotential: "$10k–$22k / mo",
    firstCustomers: "Body shops + insurance referral network",
    stageHint: "Stage 1 covers the certifications.",
  },
  {
    name: "Epoxy garage floors",
    category: "service",
    offer: "1-day install. $1,500–$4,000 per garage, 2–4/week.",
    startupCost: "Starts under $6,500",
    incomePotential: "$10k–$30k / mo",
    firstCustomers: "Door-hangers in 5 new subdivisions",
    stageHint: "Stage 6 builds the before/after ads.",
  },
  {
    name: "Mobile IV + wellness therapy",
    category: "service",
    offer: "At-home hydration & vitamin drips. $150–$300 per visit (RN partner).",
    startupCost: "Starts under $9,500",
    incomePotential: "$8k–$18k / mo",
    firstCustomers: "Yoga studios, corporate offices, bachelorette planners",
    stageHint: "Stage 1 sorts the medical structure.",
  },
  {
    name: "Home-organization concierge",
    category: "service",
    offer: "Closet, pantry, garage. $1,200–$3,500 per project.",
    startupCost: "Starts under $1,500",
    incomePotential: "$5k–$12k / mo",
    firstCustomers: "Realtor referrals + 3 free portfolio jobs for IG",
    stageHint: "Stage 5 builds your portfolio site.",
  },
  {
    name: "Senior tech help — home visits",
    category: "service",
    offer: "1-hour visits. Phones, TVs, Wi-Fi. $75/hour, 4 visits/day.",
    startupCost: "Starts under $200",
    incomePotential: "$3k–$7k / mo",
    firstCustomers: "Church bulletins, senior centers, NextDoor",
    stageHint: "Stage 2 writes your offer in plain English.",
  },
  {
    name: "Senior errand & concierge service",
    category: "service",
    offer: "Groceries, prescriptions, rides. $35/hour, 6 hrs/day.",
    startupCost: "Starts under $400",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Doctor offices, churches, NextDoor",
    stageHint: "Stage 2 builds the packages.",
  },
  {
    name: "Mobile notary + loan signing agent",
    category: "service",
    offer: "On-site signings. $100–$200 per appointment.",
    startupCost: "Starts under $700",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Title companies, real estate offices, Snapdocs",
    stageHint: "Stage 1 walks you through credentials.",
  },
  {
    name: "Pet sitting & dog walking",
    category: "service",
    offer: "30-min walks + overnights. $25 walk, $90 overnight.",
    startupCost: "Starts under $400",
    incomePotential: "$2k–$6k / mo",
    firstCustomers: "Rover, NextDoor, vet bulletin boards",
    stageHint: "Stage 5 builds your booking page.",
  },
  {
    name: "Route-based lawn care",
    category: "service",
    offer: "Two yards a day, same street. $60–$90 per cut.",
    startupCost: "Starts under $3,500",
    incomePotential: "$5k–$12k / mo (in season)",
    firstCustomers: "Door hangers on one street, then the next",
    stageHint: "Stage 7 builds your route plan.",
  },
  {
    name: "EV-charger install referral business",
    category: "service",
    offer: "Sell + coordinate home installs. $200–$500 per referral, partner electrician.",
    startupCost: "Starts under $500",
    incomePotential: "$3k–$10k / mo",
    firstCustomers: "EV owner FB groups + 3 dealership partnerships",
    stageHint: "Stage 2 builds the referral pitch.",
  },
  {
    name: "Christmas light install (Oct–Jan)",
    category: "service",
    offer: "Install + take-down + storage. $400–$1,500 per home.",
    startupCost: "Starts under $4,000",
    incomePotential: "$15k–$50k / season",
    firstCustomers: "Door hangers in 3 nicer neighborhoods in September",
    stageHint: "Stage 6 builds the fall ads.",
  },
  {
    name: "Faith-based event & wedding planning",
    category: "service",
    offer: "Full-service weddings + church events. $2,500–$8,000 per event.",
    startupCost: "Starts under $1,500",
    incomePotential: "$5k–$15k / mo (seasonal)",
    firstCustomers: "Pastor referrals + 3 styled-shoot portfolio photos",
    stageHint: "Stage 5 builds your portfolio site.",
  },
  {
    name: "Real estate drone + 3D Matterport tours",
    category: "service",
    offer: "Listing photo + drone + virtual tour. $400–$800 per home.",
    startupCost: "Starts under $4,500 (drone + camera)",
    incomePotential: "$6k–$15k / mo",
    firstCustomers: "3 agents at one brokerage. Word travels fast.",
    stageHint: "Stage 6 builds your sample reel.",
  },

  // ============== FOOD & HANDS (7) ==============
  {
    name: "Ghost-kitchen brand on DoorDash",
    category: "food",
    offer: "Single-concept menu cooked from a shared kitchen. $9–$18 per ticket.",
    startupCost: "Starts under $7,500",
    incomePotential: "$8k–$20k / mo",
    firstCustomers: "DoorDash + IG ads inside a 5-mile radius",
    stageHint: "Stage 2 builds the concept + menu.",
  },
  {
    name: "Weekly corporate-lunch route",
    category: "food",
    offer: "5 offices, 5 days, 30 lunches/office. $15–$18 per lunch.",
    startupCost: "Starts under $6,000",
    incomePotential: "$10k–$22k / mo",
    firstCustomers: "Office managers in 5 buildings near you",
    stageHint: "Stage 7 maps the weekly route.",
  },
  {
    name: "Sunday meal prep for working moms",
    category: "food",
    offer: "5 dinners, dropped off Sunday. $95/week per family.",
    startupCost: "Starts under $1,000 (cottage law)",
    incomePotential: "$3k–$7k / mo",
    firstCustomers: "10 moms in your subdivision, then their friends",
    stageHint: "Stage 4 builds the weekly delivery flow.",
  },
  {
    name: "Functional baking — gluten-free & sourdough subs",
    category: "food",
    offer: "Weekly bread/treat drops. $30/week, 60+ subscribers.",
    startupCost: "Starts under $1,500 (cottage law)",
    incomePotential: "$2k–$6k / mo",
    firstCustomers: "Celiac + wellness groups on Facebook",
    stageHint: "Stage 5 builds the subscription page.",
  },
  {
    name: "Caribbean lunch plates at office parks",
    category: "food",
    offer: "Pre-order Friday lunches. $15/plate, 40 plates/day.",
    startupCost: "Starts under $1,500",
    incomePotential: "$2k–$6k / mo (1 day a week)",
    firstCustomers: "One office park, one email blast, one Friday",
    stageHint: "Stage 2 builds the menu & pricing.",
  },
  {
    name: "Wedding cookie + favor boxes",
    category: "food",
    offer: "Custom decorated cookies. $5–$10 each, 50+ orders.",
    startupCost: "Starts under $600 (cottage law)",
    incomePotential: "$2k–$6k / mo (seasonal)",
    firstCustomers: "Wedding planners, IG, The Knot",
    stageHint: "Stage 5 builds your portfolio site.",
  },
  {
    name: "Cold-pressed juice subscription",
    category: "food",
    offer: "Weekly 6-pack drop-off. $45/week per subscriber.",
    startupCost: "Starts under $3,500",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "Yoga studios, gyms, IG fitness accounts",
    stageHint: "Stage 5 builds your subscription page.",
  },

  // ============== SIDE → FULL-TIME (5) ==============
  {
    name: "Short-form video agency for med-spas",
    category: "side",
    offer: "12 reels/mo + ads. $2,000/mo retainer per client.",
    startupCost: "Starts under $1,500",
    incomePotential: "$8k–$20k / mo",
    firstCustomers: "DM 30 med-spas with a free sample reel",
    stageHint: "Stage 7 gets your first 3 retainers.",
  },
  {
    name: "Amazon FBA wholesale",
    category: "side",
    offer: "Buy real brands in bulk, sell on Amazon. 20–35% margins.",
    startupCost: "Starts under $9,000",
    incomePotential: "$3k–$15k / mo",
    firstCustomers: "Amazon's traffic — your first SKU live in 30 days",
    stageHint: "Stage 1 gets the seller account + LLC right.",
  },
  {
    name: "Resume + LinkedIn rewrites",
    category: "side",
    offer: "Career-switcher package. $450 per client.",
    startupCost: "Starts under $100",
    incomePotential: "$2k–$6k / mo",
    firstCustomers: "LinkedIn posts, alumni groups, career-change Reddit",
    stageHint: "Stage 2 writes your one-sentence offer.",
  },
  {
    name: "Wedding officiant + ceremony coach",
    category: "side",
    offer: "Custom ceremony + rehearsal. $500–$1,000 per wedding.",
    startupCost: "Starts under $200",
    incomePotential: "$2k–$6k / mo (seasonal)",
    firstCustomers: "Wedding planners, Zola, The Knot",
    stageHint: "Stage 5 builds your booking site.",
  },
  {
    name: "Short-form video editing for realtors",
    category: "side",
    offer: "8 reels/mo, captions + music. $700/mo retainer.",
    startupCost: "Starts under $300",
    incomePotential: "$3k–$8k / mo",
    firstCustomers: "DM 50 realtors with a free sample edit",
    stageHint: "Stage 7 gets your first 5 retainers.",
  },

  // ============== FAMILY-RUN (4) ==============
  {
    name: "Two-truck handyman crew",
    category: "family",
    offer: "Husband leads jobs, partner runs scheduling. $95/hour, 2-hr min.",
    startupCost: "Starts under $9,000 (second truck + tools)",
    incomePotential: "$10k–$22k / mo",
    firstCustomers: "Thumbtack + 50 doors in two subdivisions",
    stageHint: "Stage 7 plans the first 90 days.",
  },
  {
    name: "Husband-wife Airbnb management",
    category: "family",
    offer: "Manage 20+ short-term rentals. 15–20% of nightly revenue.",
    startupCost: "Starts under $3,000",
    incomePotential: "$8k–$18k / mo",
    firstCustomers: "Message 30 Airbnb hosts in your city directly",
    stageHint: "Stage 2 builds the pitch to hosts.",
  },
  {
    name: "Saturday family car wash",
    category: "family",
    offer: "$30 hand wash, $50 with interior. 15 cars per Saturday.",
    startupCost: "Starts under $500",
    incomePotential: "$1k–$3k / mo (1 day a week)",
    firstCustomers: "Driveway sign + church parking lot permission",
    stageHint: "Stage 4 builds the weekly workflow.",
  },
  {
    name: "Family cleaning crew for Airbnbs",
    category: "family",
    offer: "Turnovers between guests. $100–$160 per clean.",
    startupCost: "Starts under $800",
    incomePotential: "$4k–$10k / mo",
    firstCustomers: "Message 30 Airbnb hosts in your city directly",
    stageHint: "Stage 2 builds the host pitch.",
  },
];
