export type Task = {
  title: string;
  deliverable: string;
  tool: string;
  details: string[];
  takeaway?: string;
  followUp?: string;
};

export type Stage = {
  n: number;
  slug: string;
  title: string;
  shortTitle: string;
  summary: string;
  oneLiner: string;
  takeHome: string;
  walkOut: string[];
  afterWorkshop: string[];
  duration: string;
  covers: string[];
  tasks: Task[];
  bonus?: boolean;
};

// Mirrors FRAMEWORK_STAGES (src/lib/framework-deliverables.ts) so the on-site
// /schedule agenda uses the same 5 pillars + 3 bonus tracks the founder sees on
// their dashboard after registering. Titles, ordering, and numbering match the
// framework verbatim. In-room copy describes what's produced live; followUp
// describes what continues on the dashboard.
export const STAGES: Stage[] = [
  {
    n: 1,
    slug: "foundation",
    title: "Foundation",
    shortTitle: "foundation",
    oneLiner: "The bedrock every defensible startup is built on.",
    summary:
      "The one drafting stage. You write the one-page story of your startup — vision, problem, and value prop — with worksheet support and AI sharpening. Every stage after Foundation switches modes: those are mentored working sessions that review your Foundation and pressure-test whatever you bring in.",
    takeHome:
      "Your Executive Summary, Vision & Mission, Problem/Solution Brief, and Value Proposition — drafted by you, sharpened in-room, and inherited as the source of truth by every downstream stage.",
    walkOut: [
      "Executive Summary — a one-page snapshot of what you do, who it's for, how you make money, and why now",
      "Vision & Mission — the north-star statement your team, customers, and future hires can rally behind",
      "Problem / Solution Brief — the painful problem you solve and exactly how your offer removes it, in plain language",
      "Value Proposition — the single sentence that explains why a customer picks you over every alternative",
    ],
    afterWorkshop: [
      "Paste your Value Prop onto your homepage hero within 48 hours",
      "Test the Executive Summary on 3 people who fit your buyer profile — refine based on where they get confused",
    ],
    duration: "25 min",
    covers: ["Executive Summary", "Vision & Mission", "Problem/Solution", "Value Prop"],
    tasks: [
      {
        title: "Draft the Foundation four",
        deliverable:
          "Executive Summary, Vision & Mission, Problem/Solution Brief, and Value Proposition — all four saved to your dashboard's Foundation stage.",
        tool: "Foundation drafting worksheet + AI-assisted sharpener",
        details: [
          "Write the one-sentence value prop first using the [Who] + [Problem] + [Outcome] + [Unfair advantage] frame",
          "Draft vision (10-year picture) and mission (what you do every day) side by side",
          "Name the problem in the customer's own words, not yours",
          "Compose the Executive Summary last — it's a distillation of the other three",
        ],
        takeaway:
          "Your Foundation pillar complete — the 60-second story of your startup, sharp enough to open every conversation.",
        followUp:
          "Foundation deliverables land on your dashboard immediately. Revise them anytime — every downstream stage inherits this language.",
      },
    ],
  },
  {
    n: 2,
    slug: "strategy",
    title: "Strategy",
    shortTitle: "strategy",
    oneLiner: "Sized market, named buyer, first 90 days.",
    summary:
      "A mentored working session on strategy. You bring your Foundation and a first attempt at market, buyer, and wedge — staff apply an operator's lens, redirect what's fuzzy, and sharpen the plan live. You leave with a Strategy Brief, personas, and a 90-day GTM sequencer as reviewed working drafts you keep refining.",
    takeHome:
      "A reviewed Strategy Brief PDF (8–10 pages) + 5 outreach message drafts + 90-Day GTM sequencer + Persona Cards — all saved to your dashboard as working assets you continue to iterate on.",
    walkOut: [
      "Signature build: TAM/SAM/SOM sizer with your ZIP + category + price band, sourced",
      "Signature build: Persona canvas built from your pasted customer interview transcript",
      "Signature build: Competitive matrix + wedge statement drafted on screen",
      "Signature build: 90-day GTM sequencer (channel, offer, one metric per week)",
      "Ship-ready artifact: Strategy Brief PDF (8–10 pages) generated by staff + released to your dashboard",
      "Ship-ready artifact: 5 outreach messages (cold email, LinkedIn DM, warm intro ask, referral, follow-up) written in your voice",
      "Take-home kit: Persona Cards + Sequencer + Brief + Messages, all in your dashboard",
    ],
    afterWorkshop: [
      "Monday: send outreach message #1 to 10 people who fit your persona",
      "Log responses in the 90-Day Sequencer; refine hooks Friday",
      "Test your Value Prop line on 3 real buyers this week",
    ],
    duration: "25 min",
    covers: ["Market sizer", "Persona canvas", "Wedge", "90-day GTM", "5 outreach messages"],
    tasks: [
      {
        title: "Signature build — size the market, name the buyer",
        deliverable:
          "TAM/SAM/SOM sized live, Persona Canvas filled from a real customer interview, Competitive Wedge statement drafted, 90-day GTM sequencer locked.",
        tool: "TAM/SAM/SOM sizer + Persona canvas + Competitive matrix + 90-day sequencer",
        details: [
          "Enter ZIP + category + price band → sized market with cited sources on screen",
          "Paste one customer interview transcript → 2 personas with pain, budget, vocabulary",
          "Score 3 alternatives → wedge statement written from the gaps",
          "Sequence 90-day GTM week by week: channel, offer, one metric",
        ],
        takeaway: "Market sized, buyer named, wedge locked, first 90 days sequenced.",
        followUp:
          "Staff runs the Strategy Brief generator on your inputs — Brief PDF + 5 outreach messages land in your dashboard before you leave.",
      },
      {
        title: "Ship-ready artifact — Strategy Brief + 5 outreach messages",
        deliverable:
          "Strategy Brief PDF (8–10 pages) + 5-message outreach pack (DOCX) + Persona Cards + 90-Day Sequencer, generated by staff via Lovable AI and released to your dashboard.",
        tool: "Lovable AI · google/gemini-3-flash-preview — staff-run in-session",
        details: [
          "Brief includes sized market with sources, 2 personas with quotes, competitive matrix, wedge, week-by-week GTM",
          "Outreach pack: cold email, LinkedIn DM, warm intro ask, referral request, follow-up — all in your voice",
          "Persona Cards printable for the wall",
          "Everything writes back to your dashboard's Strategy stage",
        ],
        takeaway: "You leave with the asset your bank, partner, or first buyer expects.",
        followUp:
          "Monday move: send outreach message #1 to 10 personas. Log in the Sequencer. Refine Friday.",
      },
    ],
  },
  {
    n: 3,
    slug: "operations",
    title: "Operations",
    shortTitle: "operations",
    oneLiner: "The business runs on repeat — not on you.",
    summary:
      "A mentored working session on how the business runs week to week. You bring your current workflow, offer, and sales conversations — staff apply a chief-of-staff lens, question where you're the bottleneck, and redirect until the business could survive without you touching every step.",
    takeHome:
      "A reviewed Operations Playbook + Weekly Ops SOP + Sales Playbook + First-Hire SOP — working assets on your dashboard, ready for you to run for a real week and refine from what breaks.",
    walkOut: [
      "Signature build: Weekly Ops Loop mapped as Kanban (intake → produce → deliver → invoice → follow-up) with owner + tool per step",
      "Signature build: 12-month product roadmap sequenced, revenue-weighted",
      "Signature build: Sales script written (5 discovery Qs, top 3 objections with rebuttal language, close)",
      "Signature build: Monthly channel spend planner with one metric per channel",
      "Ship-ready artifact: Operations Playbook PDF (~15 pages) generated by staff",
      "Ship-ready artifact: Weekly Ops SOP as Google Doc + Notion template — checkboxes ready to run",
      "Take-home kit: printable 1-page First-Hire SOP so a helper can onboard in 30 min",
    ],
    afterWorkshop: [
      "Run one full week of your Weekly Ops SOP; log where it breaks Friday",
      "Use the Sales Playbook on 3 conversations; refine objection rebuttals from what you hear",
      "Turn off any channel not hitting its one metric within 30 days",
    ],
    duration: "25 min",
    covers: ["Weekly Ops Loop", "12-mo roadmap", "Sales script", "Channel planner", "First-Hire SOP"],
    tasks: [
      {
        title: "Signature build — Ops Loop, Roadmap, Sales, Channels",
        deliverable:
          "Weekly Ops Kanban + 12-month roadmap + Sales Playbook + Channel spend planner, all filled live.",
        tool: "Kanban builder + Roadmap sequencer + Sales script generator + Channel planner",
        details: [
          "Drag your weekly workflow into 5 columns with owner + tool per step",
          "Sequence 12 months of product releases, revenue-weighted",
          "Write 5 discovery questions, top 3 objections with rebuttal language, and your close",
          "Set monthly spend by channel + the one metric you'll watch",
        ],
        takeaway: "The business runs on paper. A first hire could take pieces off your plate.",
        followUp:
          "Staff runs the Operations Playbook generator — 15-page PDF + Weekly Ops SOP template land in your dashboard.",
      },
      {
        title: "Ship-ready artifact — Operations Playbook + First-Hire SOP",
        deliverable:
          "Operations Playbook PDF (~15 pages), Weekly Ops SOP as Google Doc + Notion, First-Hire SOP printable — all generated in-session and released to your dashboard.",
        tool: "Lovable AI · google/gemini-3-flash-preview — staff-run in-session",
        details: [
          "Playbook covers 12-month roadmap, weekly workflow SOP, sales scripts, marketing plan, delegation map",
          "Weekly Ops SOP has checkboxes for every step — copy your Google Doc, run it Monday",
          "First-Hire SOP is 1 page — hand to a helper and they can onboard in 30 min",
          "Everything writes back to your dashboard's Operations stage",
        ],
        takeaway: "You've got a business a teammate could run — not just a hustle only you can carry.",
        followUp:
          "Monday move: run one full week of the Ops SOP end-to-end. Log where it breaks; refine Friday.",
      },
    ],
  },
  {
    n: 4,
    slug: "finance",
    title: "Finance",
    shortTitle: "finance",
    oneLiner: "Bank-ready numbers, cheapest capital, deck v1.",
    summary:
      "A mentored working session on the numbers. You bring pricing, cost, cadence, and a funding hypothesis — staff apply a CFO-and-investor lens, challenge assumptions, and redirect until the model, unit economics, and capital path hold up under real scrutiny.",
    takeHome:
      "A reviewed 12-Month Pro Forma XLSX + Funding Strategy Memo + Pitch Deck v1 + Unit Economics — working assets on your dashboard, ready for the next money conversation and for you to tune as real numbers come in.",
    walkOut: [
      "Signature build: 12-month P&L with real formulas (revenue, COGS, opex, cash, runway) from your inputs",
      "Signature build: CAC / LTV calculated live for your first channel",
      "Signature build: Funding decision tree — 6 questions returns your cheapest capital path",
      "Signature build: 10-slide pitch outline auto-populated from Foundation + market size + P&L",
      "Ship-ready artifact: 12-Month Pro Forma XLSX generated by staff with live formulas",
      "Ship-ready artifact: Funding Strategy Memo PDF + Pitch Deck v1 (PPTX + Google Slides)",
      "Take-home kit: everything in your dashboard, ready for banker/SBA/investor meetings",
    ],
    afterWorkshop: [
      "Book one banker or SBA meeting this week using the Pro Forma and Memo",
      "Tune Unit Economics monthly on the dashboard as real numbers come in",
      "Send the Pitch Deck v1 to one warm connection for feedback within 7 days",
    ],
    duration: "25 min",
    covers: ["12-mo Pro Forma", "CAC/LTV", "Funding tree", "Pitch Deck v1"],
    tasks: [
      {
        title: "Signature build — P&L, Unit Economics, Funding path",
        deliverable:
          "12-month P&L + CAC/LTV + Funding Strategy chosen + 10-slide pitch outline populated.",
        tool: "P&L generator + CAC/LTV calculator + Funding decision tree + Pitch outline builder",
        details: [
          "Enter pricing, cost, cadence → 12-month P&L and cash forecast with real formulas",
          "Enter channel spend + close rate → CAC and LTV calculated live",
          "Answer 6 questions → cheapest capital path (bootstrap / SBA / grants / F&F / equity) + next-step contacts",
          "10-slide pitch outline auto-populated: problem, solution, market, offer, traction, model, GTM, team, ask, use of funds",
        ],
        takeaway: "You know when cash gets tight, which levers move it, and how you'll fund it.",
        followUp:
          "Staff runs the Finance Packet generator — Pro Forma XLSX + Funding Memo + Pitch Deck v1 land in your dashboard.",
      },
      {
        title: "Ship-ready artifact — Finance Packet (Pro Forma + Memo + Deck)",
        deliverable:
          "12-Month Pro Forma XLSX + Funding Strategy Memo PDF + Pitch Deck v1 (PPTX + Google Slides) + Unit Economics XLSX, staff-generated and released to your dashboard.",
        tool: "Lovable AI · google/gemini-3-flash-preview — pitch deck upgraded to a stronger model",
        details: [
          "Pro Forma has real formulas — change one price and the whole model updates",
          "Funding Memo picks your cheapest capital path with next-step contacts",
          "Pitch Deck v1 auto-populated from your Foundation story, market size, and model",
          "Everything writes back to your dashboard's Finance stage",
        ],
        takeaway: "You walk into any money conversation this week with the asset they expect.",
        followUp:
          "Monday move: book one banker or SBA meeting using the Pro Forma and Memo.",
      },
    ],
  },
  {
    n: 5,
    slug: "governance",
    title: "Governance",
    shortTitle: "governance",
    oneLiner: "Legally live this week.",
    summary:
      "A mentored working session on structure and risk. You bring your revenue plan, ownership picture, and top worries — staff apply a small-business-counsel lens, redirect on entity choice, walk you through the filings live, and pressure-test the risks you're most exposed to.",
    takeHome:
      "EIN confirmation + pre-filled formation doc + a reviewed Legal Kit (Operating Agreement, Terms + Privacy, Service Agreement, Risk Register, 3 advisor outreach drafts) — working assets you take to your own counsel or use as-is to move this week.",
    walkOut: [
      "Signature build: 5-question entity decision tree (LLC / S-Corp / Sole Prop) with plain-English recommendation",
      "Signature build: SOS account created, name confirmed, registered agent set, formation doc pre-filled",
      "Signature build: EIN applied for live — confirmation letter saved",
      "Signature build: Risk Register scored (likelihood × impact) with top 3 mitigations drafted",
      "Ship-ready artifact: Operating Agreement DOCX customized to your members and ownership split",
      "Ship-ready artifact: Terms of Service + Privacy Policy + 1-page Service Agreement / SOW",
      "Take-home kit: 3 personalized advisor outreach emails ready to send",
    ],
    afterWorkshop: [
      "Submit your state's formation document + filing fee from home (~10 min — skip if Sole Prop)",
      "Open the business bank account (1–7 days after entity approval)",
      "File local business license and sales-tax registration once entity is approved",
      "Send one advisor outreach email this week",
    ],
    duration: "25 min",
    covers: ["Entity chosen", "State filing packet", "EIN live", "Legal Kit", "Risk Register"],
    tasks: [
      {
        title: "Signature build — entity, filing, EIN, risk",
        deliverable:
          "Structure chosen, SOS account + pre-filled formation doc, EIN submitted live, Risk Register scored with top 3 mitigations drafted.",
        tool: "5-question entity decision tree + all-50-states SOS walk-through + IRS EIN portal + Risk scoring matrix",
        details: [
          "Answer 5 questions tuned to your revenue and salary plans → LLC / S-Corp / Sole Prop",
          "Confirm name on SOS business search → registered agent set → formation doc pre-filled",
          "Apply for EIN live — save the confirmation letter",
          "Score top 8 risks; top 3 get mitigations drafted",
        ],
        takeaway: "Structure locked, formation doc pre-filled, EIN issued, top risks defused.",
        followUp:
          "Staff runs the Legal Kit generator — OA, T&Cs, Privacy, Service Agreement, Risk Register, Advisor emails land in your dashboard.",
      },
      {
        title: "Ship-ready artifact — Legal Kit + Advisor Outreach",
        deliverable:
          "Operating Agreement DOCX + Terms of Service + Privacy Policy + 1-page Service Agreement / SOW + Risk Register PDF + 3 personalized advisor outreach emails, staff-generated and released to your dashboard.",
        tool: "Lovable AI · google/gemini-3-flash-preview — legal templates staff-reviewed before release",
        details: [
          "Operating Agreement customized to your members and ownership split",
          "Terms of Service + Privacy Policy tailored to your offer and state",
          "1-page Service Agreement / SOW ready for your first sale",
          "3 advisor outreach emails personalized to prospective advisors in your industry",
        ],
        takeaway: "You can legally sign contracts, take money, and open an advisor conversation this week.",
        followUp:
          "Monday move: submit your state's formation doc + filing fee (10 min). Open the business bank account when the entity is approved.",
      },
    ],
  },
  {
    n: 6,
    slug: "brand",
    title: "Brand",
    shortTitle: "brand",
    bonus: true,
    oneLiner: "Brand system — strategy, messaging, logo, palette — in hand.",
    summary:
      "A mentored working session on brand. You bring your Foundation, three brands you admire, and instinct about voice — staff apply a brand-lead lens, pressure-test purpose/promise/positioning, and direct the visual work until the brand system feels intentional.",
    takeHome:
      "A reviewed Brand Starter Kit — Strategy Framework, Messaging House, Visual Identity Brief, 3 logo concepts, palette + type pairing, and a Voice & Tone one-pager — on your dashboard as working drafts you iterate on and hand to a designer.",
    walkOut: [
      "Signature build: Brand Strategy Framework filled live (Purpose · Promise · Audience · Positioning)",
      "Signature build: Messaging House assembled from your Value Prop and Personas",
      "Signature build: Visual direction chosen from 3 AI-generated moodboards",
      "Signature build: 3 logo concepts + color palette + type pairing generated in-room",
      "Ship-ready artifact: Brand Starter Kit released to your dashboard",
      "Take-home kit: everything above, ready to drop into your existing site or profiles",
    ],
    afterWorkshop: [
      "Pick your favorite logo concept; iterate one round on your dashboard this week",
      "Drop palette + fonts into your existing site or social profiles within 48 hours",
      "Complete the full Brand Guidelines Book on your dashboard this week",
    ],
    duration: "Bonus — in-room artifact + dashboard finish",
    covers: ["Strategy Framework", "Messaging House", "Logo concepts", "Palette + fonts", "Voice"],
    tasks: [
      {
        title: "Signature build — Strategy, Messaging, Visual direction",
        deliverable:
          "Brand Strategy Framework + Messaging House + Visual Identity Brief drafted live; 3 logo concepts and palette generated in-room.",
        tool: "Brand Strategy canvas + Messaging House builder + AI moodboard/logo generator",
        details: [
          "Purpose · Promise · Audience · Positioning drafted on a single canvas",
          "Headline + 3 supporting messages + 3 proof points assembled from Value Prop and Personas",
          "Pick 1 of 3 AI-generated moodboards; visual direction locked",
          "3 logo concepts + palette + type pairing generated live",
        ],
        takeaway: "A brand system, not stickers — with strategy, messages, and visuals aligned.",
        followUp:
          "Staff releases the Brand Starter Kit to your dashboard. Full Guidelines Book continues there.",
      },
      {
        title: "Ship-ready artifact — Brand Starter Kit",
        deliverable:
          "Brand Strategy Framework PDF + Messaging House PDF + Visual Identity Brief DOCX + 3 logo concepts (PNG + SVG) + palette + type pairing + Voice & Tone one-pager.",
        tool: "Lovable AI · google/gemini-3-flash-preview + AI image generation for logos and moodboards",
        details: [
          "Strategy Framework and Messaging House writeable-back on your dashboard",
          "Visual Identity Brief ready for a designer OR to paste into an AI branding tool",
          "Logo concepts as PNG + SVG for immediate use",
          "Palette (hex codes) + Google Fonts links + Voice & Tone one-pager with do/don't examples",
        ],
        takeaway: "You leave with a working brand — not a preview.",
        followUp:
          "Monday move: pick your favorite logo, drop palette + fonts into your existing site/social profiles.",
      },
    ],
  },
  {
    n: 7,
    slug: "marketing",
    title: "Marketing",
    shortTitle: "marketing",
    bonus: true,
    oneLiner: "Website shipped this weekend.",
    summary:
      "A mentored working session on your website plan. You bring your Foundation, Strategy, and Brand — staff apply a product-and-web lens, review sitemap and CTAs, and direct you toward a build spec you can actually scaffold with an AI builder over a weekend.",
    takeHome:
      "A reviewed Website Package — PRD, AI-builder prompts for Lovable/Bolt/v0, a copy deck in your voice, and a Weekend Build Checklist — on your dashboard as a working brief you edit before you build.",
    walkOut: [
      "Signature build: sitemap picked from 3 templates matched to your business model",
      "Signature build: CTAs + integrations chosen (payments, email, analytics)",
      "Signature build: PRD auto-assembled — pages, sections, copy blocks, CTAs, image briefs",
      "Signature build: Copy Deck writes every H1/H2/body in your brand voice",
      "Ship-ready artifact: AI-builder Prompt Pack (3 prompts) for Lovable, Bolt, and v0",
      "Take-home kit: Weekend Build Checklist (Fri night → Sun evening → live)",
    ],
    afterWorkshop: [
      "This weekend: paste your prompt into Lovable/Bolt/v0 and scaffold the site",
      "Wire payments, email, and analytics from the recommended stack",
      "Publish v1 by Sunday evening; iterate copy next week",
    ],
    duration: "Bonus — in-room artifact + weekend build",
    covers: ["Website PRD", "AI-builder Prompt Pack", "Copy Deck", "Weekend Checklist"],
    tasks: [
      {
        title: "Signature build — sitemap, PRD, Copy Deck",
        deliverable:
          "Sitemap + integrations chosen, PRD assembled, Copy Deck written, AI-builder prompt pack generated.",
        tool: "Sitemap picker + PRD generator + Copy Deck writer + AI-builder prompt composer",
        details: [
          "Pick your sitemap from 3 templates matched to your business model",
          "Select CTAs and integrations (payments, email, analytics)",
          "PRD auto-assembles from Foundation + Strategy + Brand — pages, sections, image briefs, CTAs",
          "Copy Deck writes every H1/H2/body in your brand voice",
        ],
        takeaway: "You skip the $20K agency quote and launch a real revenue-ready site in a weekend.",
        followUp:
          "Staff releases the Website Package to your dashboard. Attendees with a laptop can start scaffolding in-room.",
      },
      {
        title: "Ship-ready artifact — Website Package",
        deliverable:
          "Website PRD (PDF) + AI-builder Prompt Pack (3 prompts for Lovable, Bolt, v0) + Copy Deck DOCX + Weekend Build Checklist.",
        tool: "Lovable AI · google/gemini-3-flash-preview",
        details: [
          "PRD covers full pages, sections, copy blocks, CTAs, and image briefs",
          "Prompt Pack tuned for each builder — copy-paste to scaffold",
          "Copy Deck has every page's H1/H2/body already written in your voice",
          "Weekend Build Checklist: Fri night → Sun evening → live",
        ],
        takeaway: "By Sunday evening, your site is live and taking money.",
        followUp:
          "Monday move: connect payments, email, and analytics from the recommended stack.",
      },
    ],
  },
  {
    n: 8,
    slug: "social-content",
    title: "Social & Content",
    shortTitle: "social",
    bonus: true,
    oneLiner: "Distribution engine live — 14 posts written, 90-day calendar ready.",
    summary:
      "A mentored working session on distribution. You bring your Strategy and Brand — staff apply a distribution-lead lens, redirect your pillars, sharpen hooks, and direct a 90-day plan you can actually keep up with.",
    takeHome:
      "A reviewed Distribution Kit — Content Pillars, 90-day calendar draft, 14 written posts, Launch Week kit, Paid Ads Starter, and launch graphics — on your dashboard as working drafts you edit before you schedule.",
    walkOut: [
      "Signature build: 3–5 Content Pillars generated from Positioning + Personas",
      "Signature build: 90-day calendar CSV auto-drafted with hooks, formats, visuals",
      "Signature build: First 14 posts fully written (LinkedIn + Instagram variants)",
      "Signature build: Launch Week Kit assembled (announcement, 5 captions, 3 emails, share-with-friends)",
      "Ship-ready artifact: Paid Ads Starter — 3 target segments, 5 hooks, budget guardrails",
      "Ship-ready artifact: 5 AI-generated launch graphics sized for LinkedIn/IG/Twitter",
      "Take-home kit: everything importable to your tools; posts can be scheduled in room",
    ],
    afterWorkshop: [
      "Schedule the first 14 posts using the calendar CSV",
      "Send your announcement email Tuesday morning",
      "Launch your first paid-ads test using the Starter once your site is live",
    ],
    duration: "Bonus — in-room artifact + dashboard finish",
    covers: ["Pillars", "90-day calendar", "14 posts", "Launch Week", "Paid Ads Starter", "Launch graphics"],
    tasks: [
      {
        title: "Signature build — Pillars, 14 posts, Launch Week",
        deliverable:
          "3–5 Content Pillars + first 14 posts written + Launch Week kit assembled + Paid Ads Starter drafted + 5 launch graphics generated.",
        tool: "Pillar generator + calendar drafter + post writer + Launch Kit assembler + Ads Starter + AI image generation",
        details: [
          "Pillars generated from Positioning + Personas — 3–5 themes locked",
          "90-day calendar CSV auto-drafted (Buffer/Later/Notion-importable)",
          "First 14 posts written in LinkedIn + Instagram variants",
          "Launch Week: announcement post, 5 captions, 3 email templates, share-with-friends message, 5 graphics",
        ],
        takeaway: "You launch loud, not quietly — with 14 posts scheduled and a Launch Week ready to go.",
        followUp:
          "Staff releases the Distribution Kit to your dashboard. Weeks 3–12 finish there.",
      },
      {
        title: "Ship-ready artifact — Distribution Kit",
        deliverable:
          "Content Pillars PDF + 90-Day Calendar CSV + First 14 Posts DOCX + Launch Week Kit + Paid Ads Starter + 5 launch graphics (PNG).",
        tool: "Lovable AI · google/gemini-3-flash-preview + AI image generation for launch graphics",
        details: [
          "Pillars and calendar writeable-back on your dashboard",
          "14 posts publishable this week; schedule in-room if you connect your account",
          "Launch Week kit lands your opening days with prepared content",
          "Paid Ads Starter: 3 targets, 5 ad hooks, budget guardrails tuned to your unit economics",
        ],
        takeaway: "The distribution engine is live — attention earned on repeat, not paid for each month.",
        followUp:
          "Monday move: schedule the first 14 posts; send the announcement email Tuesday.",
      },
    ],
  },
];
