import { useQuery } from "@tanstack/react-query";
import type { BriefBlock } from "@/lib/brief-blocks";
import { ChevronRight, Pencil, Sparkles } from "lucide-react";

type SummaryResult = { summary: string; bullets: string[]; cached?: boolean };

type Props = {
  block: BriefBlock;
  blockIndex: number; // 1-based
  totalBlocks: number;
  summarize: () => Promise<SummaryResult>;
  cacheKey: ReadonlyArray<unknown>;
  onContinue: () => void;
  onEdit: () => void;
  editLabel?: string;
};

export function BlockCheckpoint({
  block,
  blockIndex,
  totalBlocks,
  summarize,
  cacheKey,
  onContinue,
  onEdit,
  editLabel = "Edit my answers",
}: Props) {
  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: ["brief", "summary", ...cacheKey],
    queryFn: () => summarize(),
    staleTime: 1000 * 60 * 10,
    retry: 1,
  });

  return (
    <div className="space-y-8">
      <div>
        <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          Checkpoint · Block {blockIndex} of {totalBlocks}
        </div>
        <h1 className="mt-2 text-3xl md:text-4xl font-semibold tracking-tight leading-tight">
          {block.checkpointHeading}
        </h1>
      </div>

      <div className="rounded-2xl border border-border bg-card p-6 md:p-8">
        <div className="flex items-center gap-2 text-xs text-muted-foreground mb-4">
          <Sparkles className="h-3.5 w-3.5" />
          Generated by your AI assistant
        </div>

        {isLoading || isFetching ? (
          <div className="space-y-3">
            <div className="h-4 bg-muted/40 rounded animate-pulse w-11/12" />
            <div className="h-4 bg-muted/40 rounded animate-pulse w-10/12" />
            <div className="h-4 bg-muted/40 rounded animate-pulse w-9/12" />
          </div>
        ) : isError ? (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">
              We couldn't generate a recap, but your answers are saved.
              {error instanceof Error ? ` (${error.message})` : ""}
            </p>
            <button onClick={() => refetch()} className="text-sm text-primary hover:underline">Try again</button>
          </div>
        ) : data ? (
          <div className="space-y-5">
            <p className="text-base leading-relaxed text-foreground whitespace-pre-wrap">{data.summary}</p>
            {data.bullets?.length ? (
              <ul className="space-y-2 pl-1">
                {data.bullets.map((b, i) => (
                  <li key={i} className="flex gap-3 text-sm text-foreground/90">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-primary shrink-0" />
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            ) : null}
          </div>
        ) : null}
      </div>

      <div className="flex flex-col-reverse sm:flex-row sm:items-center sm:justify-between gap-3">
        <button
          onClick={onEdit}
          className="inline-flex items-center gap-1.5 rounded-lg px-4 py-2.5 text-sm text-muted-foreground hover:text-foreground min-h-[44px]"
        >
          <Pencil className="h-4 w-4" /> {editLabel}
        </button>
        <button
          onClick={onContinue}
          className="inline-flex items-center justify-center gap-1.5 rounded-xl bg-primary px-6 py-3 text-base font-medium text-primary-foreground hover:opacity-90 min-h-[44px]"
        >
          Sounds right — keep going <ChevronRight className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
}
