/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardWorkflowRouteImport } from './routes/_authenticated/dashboard.workflow'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardMediaRouteImport } from './routes/_authenticated/dashboard.media'
import { Route as AuthenticatedDashboardGoalsRouteImport } from './routes/_authenticated/dashboard.goals'
import { Route as AuthenticatedDashboardFilingRouteImport } from './routes/_authenticated/dashboard.filing'
import { Route as AuthenticatedDashboardFilesRouteImport } from './routes/_authenticated/dashboard.files'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard.documents'
import { Route as AuthenticatedDashboardDeliverablesRouteImport } from './routes/_authenticated/dashboard.deliverables'
import { Route as AuthenticatedDashboardDayRouteImport } from './routes/_authenticated/dashboard.day'
import { Route as AuthenticatedDashboardBriefRouteImport } from './routes/_authenticated/dashboard.brief'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicHooksPublishDueDeliverablesRouteImport } from './routes/api/public/hooks/publish-due-deliverables'
import { Route as AuthenticatedDashboardWorkflowKeyRouteImport } from './routes/_authenticated/dashboard.workflow.$key'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminReviewRouteImport } from './routes/_authenticated/_admin/admin.review'
import { Route as AuthenticatedAdminAdminRegistrationsRouteImport } from './routes/_authenticated/_admin/admin.registrations'
import { Route as AuthenticatedAdminAdminMediaRouteImport } from './routes/_authenticated/_admin/admin.media'
import { Route as AuthenticatedAdminAdminCohortsRouteImport } from './routes/_authenticated/_admin/admin.cohorts'
import { Route as AuthenticatedAdminAdminAttendeesRouteImport } from './routes/_authenticated/_admin/admin.attendees'
import { Route as AuthenticatedAdminAdminCohortsTestRouteImport } from './routes/_authenticated/_admin/admin.cohorts.test'
import { Route as AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.index'
import { Route as AuthenticatedAdminAdminAttendeesUserIdWorkflowRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.workflow'
import { Route as AuthenticatedAdminAdminAttendeesUserIdMediaRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.media'
import { Route as AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.deliverables.$key'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWorkflowRoute =
  AuthenticatedDashboardWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMediaRoute =
  AuthenticatedDashboardMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGoalsRoute =
  AuthenticatedDashboardGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFilingRoute =
  AuthenticatedDashboardFilingRouteImport.update({
    id: '/filing',
    path: '/filing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFilesRoute =
  AuthenticatedDashboardFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDeliverablesRoute =
  AuthenticatedDashboardDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDayRoute =
  AuthenticatedDashboardDayRouteImport.update({
    id: '/day',
    path: '/day',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBriefRoute =
  AuthenticatedDashboardBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksPublishDueDeliverablesRoute =
  ApiPublicHooksPublishDueDeliverablesRouteImport.update({
    id: '/api/public/hooks/publish-due-deliverables',
    path: '/api/public/hooks/publish-due-deliverables',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardWorkflowKeyRoute =
  AuthenticatedDashboardWorkflowKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AuthenticatedDashboardWorkflowRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminReviewRoute =
  AuthenticatedAdminAdminReviewRouteImport.update({
    id: '/admin/review',
    path: '/admin/review',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRegistrationsRoute =
  AuthenticatedAdminAdminRegistrationsRouteImport.update({
    id: '/admin/registrations',
    path: '/admin/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminMediaRoute =
  AuthenticatedAdminAdminMediaRouteImport.update({
    id: '/admin/media',
    path: '/admin/media',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminCohortsRoute =
  AuthenticatedAdminAdminCohortsRouteImport.update({
    id: '/admin/cohorts',
    path: '/admin/cohorts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesRoute =
  AuthenticatedAdminAdminAttendeesRouteImport.update({
    id: '/admin/attendees',
    path: '/admin/attendees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminCohortsTestRoute =
  AuthenticatedAdminAdminCohortsTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthenticatedAdminAdminCohortsRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdIndexRoute =
  AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute =
  AuthenticatedAdminAdminAttendeesUserIdWorkflowRouteImport.update({
    id: '/$userId/workflow',
    path: '/$userId/workflow',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdMediaRoute =
  AuthenticatedAdminAdminAttendeesUserIdMediaRouteImport.update({
    id: '/$userId/media',
    path: '/$userId/media',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute =
  AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport.update({
    id: '/$userId/deliverables/$key',
    path: '/$userId/deliverables/$key',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/brief': typeof AuthenticatedDashboardBriefRoute
  '/dashboard/day': typeof AuthenticatedDashboardDayRoute
  '/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/files': typeof AuthenticatedDashboardFilesRoute
  '/dashboard/filing': typeof AuthenticatedDashboardFilingRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/workflow': typeof AuthenticatedDashboardWorkflowRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/admin/cohorts': typeof AuthenticatedAdminAdminCohortsRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminAdminMediaRoute
  '/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/dashboard/workflow/$key': typeof AuthenticatedDashboardWorkflowKeyRoute
  '/api/public/hooks/publish-due-deliverables': typeof ApiPublicHooksPublishDueDeliverablesRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/cohorts/test': typeof AuthenticatedAdminAdminCohortsTestRoute
  '/admin/attendees/$userId/media': typeof AuthenticatedAdminAdminAttendeesUserIdMediaRoute
  '/admin/attendees/$userId/workflow': typeof AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute
  '/admin/attendees/$userId/': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/brief': typeof AuthenticatedDashboardBriefRoute
  '/dashboard/day': typeof AuthenticatedDashboardDayRoute
  '/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/files': typeof AuthenticatedDashboardFilesRoute
  '/dashboard/filing': typeof AuthenticatedDashboardFilingRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/workflow': typeof AuthenticatedDashboardWorkflowRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/admin/cohorts': typeof AuthenticatedAdminAdminCohortsRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminAdminMediaRoute
  '/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/dashboard/workflow/$key': typeof AuthenticatedDashboardWorkflowKeyRoute
  '/api/public/hooks/publish-due-deliverables': typeof ApiPublicHooksPublishDueDeliverablesRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/cohorts/test': typeof AuthenticatedAdminAdminCohortsTestRoute
  '/admin/attendees/$userId/media': typeof AuthenticatedAdminAdminAttendeesUserIdMediaRoute
  '/admin/attendees/$userId/workflow': typeof AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute
  '/admin/attendees/$userId': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/brief': typeof AuthenticatedDashboardBriefRoute
  '/_authenticated/dashboard/day': typeof AuthenticatedDashboardDayRoute
  '/_authenticated/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/files': typeof AuthenticatedDashboardFilesRoute
  '/_authenticated/dashboard/filing': typeof AuthenticatedDashboardFilingRoute
  '/_authenticated/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/_authenticated/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/workflow': typeof AuthenticatedDashboardWorkflowRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_admin/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/_authenticated/_admin/admin/cohorts': typeof AuthenticatedAdminAdminCohortsRouteWithChildren
  '/_authenticated/_admin/admin/media': typeof AuthenticatedAdminAdminMediaRoute
  '/_authenticated/_admin/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/_authenticated/_admin/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/dashboard/workflow/$key': typeof AuthenticatedDashboardWorkflowKeyRoute
  '/api/public/hooks/publish-due-deliverables': typeof ApiPublicHooksPublishDueDeliverablesRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/cohorts/test': typeof AuthenticatedAdminAdminCohortsTestRoute
  '/_authenticated/_admin/admin/attendees/$userId/media': typeof AuthenticatedAdminAdminAttendeesUserIdMediaRoute
  '/_authenticated/_admin/admin/attendees/$userId/workflow': typeof AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute
  '/_authenticated/_admin/admin/attendees/$userId/': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/dashboard/brief'
    | '/dashboard/day'
    | '/dashboard/deliverables'
    | '/dashboard/documents'
    | '/dashboard/files'
    | '/dashboard/filing'
    | '/dashboard/goals'
    | '/dashboard/media'
    | '/dashboard/profile'
    | '/dashboard/workflow'
    | '/dashboard/'
    | '/admin/attendees'
    | '/admin/cohorts'
    | '/admin/media'
    | '/admin/registrations'
    | '/admin/review'
    | '/admin/users'
    | '/dashboard/workflow/$key'
    | '/api/public/hooks/publish-due-deliverables'
    | '/admin/'
    | '/admin/cohorts/test'
    | '/admin/attendees/$userId/media'
    | '/admin/attendees/$userId/workflow'
    | '/admin/attendees/$userId/'
    | '/admin/attendees/$userId/deliverables/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/dashboard/brief'
    | '/dashboard/day'
    | '/dashboard/deliverables'
    | '/dashboard/documents'
    | '/dashboard/files'
    | '/dashboard/filing'
    | '/dashboard/goals'
    | '/dashboard/media'
    | '/dashboard/profile'
    | '/dashboard/workflow'
    | '/dashboard'
    | '/admin/attendees'
    | '/admin/cohorts'
    | '/admin/media'
    | '/admin/registrations'
    | '/admin/review'
    | '/admin/users'
    | '/dashboard/workflow/$key'
    | '/api/public/hooks/publish-due-deliverables'
    | '/admin'
    | '/admin/cohorts/test'
    | '/admin/attendees/$userId/media'
    | '/admin/attendees/$userId/workflow'
    | '/admin/attendees/$userId'
    | '/admin/attendees/$userId/deliverables/$key'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/brief'
    | '/_authenticated/dashboard/day'
    | '/_authenticated/dashboard/deliverables'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/files'
    | '/_authenticated/dashboard/filing'
    | '/_authenticated/dashboard/goals'
    | '/_authenticated/dashboard/media'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/workflow'
    | '/_authenticated/dashboard/'
    | '/_authenticated/_admin/admin/attendees'
    | '/_authenticated/_admin/admin/cohorts'
    | '/_authenticated/_admin/admin/media'
    | '/_authenticated/_admin/admin/registrations'
    | '/_authenticated/_admin/admin/review'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/dashboard/workflow/$key'
    | '/api/public/hooks/publish-due-deliverables'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/cohorts/test'
    | '/_authenticated/_admin/admin/attendees/$userId/media'
    | '/_authenticated/_admin/admin/attendees/$userId/workflow'
    | '/_authenticated/_admin/admin/attendees/$userId/'
    | '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksPublishDueDeliverablesRoute: typeof ApiPublicHooksPublishDueDeliverablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/workflow': {
      id: '/_authenticated/dashboard/workflow'
      path: '/workflow'
      fullPath: '/dashboard/workflow'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/media': {
      id: '/_authenticated/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof AuthenticatedDashboardMediaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/goals': {
      id: '/_authenticated/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof AuthenticatedDashboardGoalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/filing': {
      id: '/_authenticated/dashboard/filing'
      path: '/filing'
      fullPath: '/dashboard/filing'
      preLoaderRoute: typeof AuthenticatedDashboardFilingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/files': {
      id: '/_authenticated/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof AuthenticatedDashboardFilesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/deliverables': {
      id: '/_authenticated/dashboard/deliverables'
      path: '/deliverables'
      fullPath: '/dashboard/deliverables'
      preLoaderRoute: typeof AuthenticatedDashboardDeliverablesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/day': {
      id: '/_authenticated/dashboard/day'
      path: '/day'
      fullPath: '/dashboard/day'
      preLoaderRoute: typeof AuthenticatedDashboardDayRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/brief': {
      id: '/_authenticated/dashboard/brief'
      path: '/brief'
      fullPath: '/dashboard/brief'
      preLoaderRoute: typeof AuthenticatedDashboardBriefRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/publish-due-deliverables': {
      id: '/api/public/hooks/publish-due-deliverables'
      path: '/api/public/hooks/publish-due-deliverables'
      fullPath: '/api/public/hooks/publish-due-deliverables'
      preLoaderRoute: typeof ApiPublicHooksPublishDueDeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/workflow/$key': {
      id: '/_authenticated/dashboard/workflow/$key'
      path: '/$key'
      fullPath: '/dashboard/workflow/$key'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowKeyRouteImport
      parentRoute: typeof AuthenticatedDashboardWorkflowRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/review': {
      id: '/_authenticated/_admin/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/registrations': {
      id: '/_authenticated/_admin/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/media': {
      id: '/_authenticated/_admin/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/cohorts': {
      id: '/_authenticated/_admin/admin/cohorts'
      path: '/admin/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AuthenticatedAdminAdminCohortsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/attendees': {
      id: '/_authenticated/_admin/admin/attendees'
      path: '/admin/attendees'
      fullPath: '/admin/attendees'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/cohorts/test': {
      id: '/_authenticated/_admin/admin/cohorts/test'
      path: '/test'
      fullPath: '/admin/cohorts/test'
      preLoaderRoute: typeof AuthenticatedAdminAdminCohortsTestRouteImport
      parentRoute: typeof AuthenticatedAdminAdminCohortsRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/': {
      id: '/_authenticated/_admin/admin/attendees/$userId/'
      path: '/$userId'
      fullPath: '/admin/attendees/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/workflow': {
      id: '/_authenticated/_admin/admin/attendees/$userId/workflow'
      path: '/$userId/workflow'
      fullPath: '/admin/attendees/$userId/workflow'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdWorkflowRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/media': {
      id: '/_authenticated/_admin/admin/attendees/$userId/media'
      path: '/$userId/media'
      fullPath: '/admin/attendees/$userId/media'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdMediaRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key': {
      id: '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key'
      path: '/$userId/deliverables/$key'
      fullPath: '/admin/attendees/$userId/deliverables/$key'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
  }
}

interface AuthenticatedAdminAdminAttendeesRouteChildren {
  AuthenticatedAdminAdminAttendeesUserIdMediaRoute: typeof AuthenticatedAdminAdminAttendeesUserIdMediaRoute
  AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute: typeof AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute
  AuthenticatedAdminAdminAttendeesUserIdIndexRoute: typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute: typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}

const AuthenticatedAdminAdminAttendeesRouteChildren: AuthenticatedAdminAdminAttendeesRouteChildren =
  {
    AuthenticatedAdminAdminAttendeesUserIdMediaRoute:
      AuthenticatedAdminAdminAttendeesUserIdMediaRoute,
    AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute:
      AuthenticatedAdminAdminAttendeesUserIdWorkflowRoute,
    AuthenticatedAdminAdminAttendeesUserIdIndexRoute:
      AuthenticatedAdminAdminAttendeesUserIdIndexRoute,
    AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute:
      AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute,
  }

const AuthenticatedAdminAdminAttendeesRouteWithChildren =
  AuthenticatedAdminAdminAttendeesRoute._addFileChildren(
    AuthenticatedAdminAdminAttendeesRouteChildren,
  )

interface AuthenticatedAdminAdminCohortsRouteChildren {
  AuthenticatedAdminAdminCohortsTestRoute: typeof AuthenticatedAdminAdminCohortsTestRoute
}

const AuthenticatedAdminAdminCohortsRouteChildren: AuthenticatedAdminAdminCohortsRouteChildren =
  {
    AuthenticatedAdminAdminCohortsTestRoute:
      AuthenticatedAdminAdminCohortsTestRoute,
  }

const AuthenticatedAdminAdminCohortsRouteWithChildren =
  AuthenticatedAdminAdminCohortsRoute._addFileChildren(
    AuthenticatedAdminAdminCohortsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAttendeesRoute: typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  AuthenticatedAdminAdminCohortsRoute: typeof AuthenticatedAdminAdminCohortsRouteWithChildren
  AuthenticatedAdminAdminMediaRoute: typeof AuthenticatedAdminAdminMediaRoute
  AuthenticatedAdminAdminRegistrationsRoute: typeof AuthenticatedAdminAdminRegistrationsRoute
  AuthenticatedAdminAdminReviewRoute: typeof AuthenticatedAdminAdminReviewRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAttendeesRoute:
    AuthenticatedAdminAdminAttendeesRouteWithChildren,
  AuthenticatedAdminAdminCohortsRoute:
    AuthenticatedAdminAdminCohortsRouteWithChildren,
  AuthenticatedAdminAdminMediaRoute: AuthenticatedAdminAdminMediaRoute,
  AuthenticatedAdminAdminRegistrationsRoute:
    AuthenticatedAdminAdminRegistrationsRoute,
  AuthenticatedAdminAdminReviewRoute: AuthenticatedAdminAdminReviewRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardWorkflowRouteChildren {
  AuthenticatedDashboardWorkflowKeyRoute: typeof AuthenticatedDashboardWorkflowKeyRoute
}

const AuthenticatedDashboardWorkflowRouteChildren: AuthenticatedDashboardWorkflowRouteChildren =
  {
    AuthenticatedDashboardWorkflowKeyRoute:
      AuthenticatedDashboardWorkflowKeyRoute,
  }

const AuthenticatedDashboardWorkflowRouteWithChildren =
  AuthenticatedDashboardWorkflowRoute._addFileChildren(
    AuthenticatedDashboardWorkflowRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBriefRoute: typeof AuthenticatedDashboardBriefRoute
  AuthenticatedDashboardDayRoute: typeof AuthenticatedDashboardDayRoute
  AuthenticatedDashboardDeliverablesRoute: typeof AuthenticatedDashboardDeliverablesRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardFilesRoute: typeof AuthenticatedDashboardFilesRoute
  AuthenticatedDashboardFilingRoute: typeof AuthenticatedDashboardFilingRoute
  AuthenticatedDashboardGoalsRoute: typeof AuthenticatedDashboardGoalsRoute
  AuthenticatedDashboardMediaRoute: typeof AuthenticatedDashboardMediaRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardWorkflowRoute: typeof AuthenticatedDashboardWorkflowRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBriefRoute: AuthenticatedDashboardBriefRoute,
    AuthenticatedDashboardDayRoute: AuthenticatedDashboardDayRoute,
    AuthenticatedDashboardDeliverablesRoute:
      AuthenticatedDashboardDeliverablesRoute,
    AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
    AuthenticatedDashboardFilesRoute: AuthenticatedDashboardFilesRoute,
    AuthenticatedDashboardFilingRoute: AuthenticatedDashboardFilingRoute,
    AuthenticatedDashboardGoalsRoute: AuthenticatedDashboardGoalsRoute,
    AuthenticatedDashboardMediaRoute: AuthenticatedDashboardMediaRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardWorkflowRoute:
      AuthenticatedDashboardWorkflowRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksPublishDueDeliverablesRoute:
    ApiPublicHooksPublishDueDeliverablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
