/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardGoalsRouteImport } from './routes/_authenticated/dashboard.goals'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard.documents'
import { Route as AuthenticatedDashboardDeliverablesRouteImport } from './routes/_authenticated/dashboard.deliverables'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminReviewRouteImport } from './routes/_authenticated/_admin/admin.review'
import { Route as AuthenticatedAdminAdminRegistrationsRouteImport } from './routes/_authenticated/_admin/admin.registrations'
import { Route as AuthenticatedAdminAdminAttendeesRouteImport } from './routes/_authenticated/_admin/admin.attendees'
import { Route as AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.index'
import { Route as AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport } from './routes/_authenticated/_admin/admin.attendees.$userId.deliverables.$key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGoalsRoute =
  AuthenticatedDashboardGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDeliverablesRoute =
  AuthenticatedDashboardDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminReviewRoute =
  AuthenticatedAdminAdminReviewRouteImport.update({
    id: '/admin/review',
    path: '/admin/review',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRegistrationsRoute =
  AuthenticatedAdminAdminRegistrationsRouteImport.update({
    id: '/admin/registrations',
    path: '/admin/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesRoute =
  AuthenticatedAdminAdminAttendeesRouteImport.update({
    id: '/admin/attendees',
    path: '/admin/attendees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdIndexRoute =
  AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)
const AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute =
  AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport.update({
    id: '/$userId/deliverables/$key',
    path: '/$userId/deliverables/$key',
    getParentRoute: () => AuthenticatedAdminAdminAttendeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/attendees/$userId/': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/attendees/$userId': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/deliverables': typeof AuthenticatedDashboardDeliverablesRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_admin/admin/attendees': typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  '/_authenticated/_admin/admin/registrations': typeof AuthenticatedAdminAdminRegistrationsRoute
  '/_authenticated/_admin/admin/review': typeof AuthenticatedAdminAdminReviewRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/attendees/$userId/': typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key': typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/dashboard'
    | '/dashboard/deliverables'
    | '/dashboard/documents'
    | '/dashboard/goals'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/admin/attendees'
    | '/admin/registrations'
    | '/admin/review'
    | '/admin/users'
    | '/admin/'
    | '/admin/attendees/$userId/'
    | '/admin/attendees/$userId/deliverables/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/dashboard/deliverables'
    | '/dashboard/documents'
    | '/dashboard/goals'
    | '/dashboard/profile'
    | '/dashboard'
    | '/admin/attendees'
    | '/admin/registrations'
    | '/admin/review'
    | '/admin/users'
    | '/admin'
    | '/admin/attendees/$userId'
    | '/admin/attendees/$userId/deliverables/$key'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/deliverables'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/goals'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/'
    | '/_authenticated/_admin/admin/attendees'
    | '/_authenticated/_admin/admin/registrations'
    | '/_authenticated/_admin/admin/review'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/attendees/$userId/'
    | '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/goals': {
      id: '/_authenticated/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof AuthenticatedDashboardGoalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/deliverables': {
      id: '/_authenticated/dashboard/deliverables'
      path: '/deliverables'
      fullPath: '/dashboard/deliverables'
      preLoaderRoute: typeof AuthenticatedDashboardDeliverablesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/review': {
      id: '/_authenticated/_admin/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/registrations': {
      id: '/_authenticated/_admin/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/attendees': {
      id: '/_authenticated/_admin/admin/attendees'
      path: '/admin/attendees'
      fullPath: '/admin/attendees'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/': {
      id: '/_authenticated/_admin/admin/attendees/$userId/'
      path: '/$userId'
      fullPath: '/admin/attendees/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
    '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key': {
      id: '/_authenticated/_admin/admin/attendees/$userId/deliverables/$key'
      path: '/$userId/deliverables/$key'
      fullPath: '/admin/attendees/$userId/deliverables/$key'
      preLoaderRoute: typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAttendeesRoute
    }
  }
}

interface AuthenticatedAdminAdminAttendeesRouteChildren {
  AuthenticatedAdminAdminAttendeesUserIdIndexRoute: typeof AuthenticatedAdminAdminAttendeesUserIdIndexRoute
  AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute: typeof AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute
}

const AuthenticatedAdminAdminAttendeesRouteChildren: AuthenticatedAdminAdminAttendeesRouteChildren =
  {
    AuthenticatedAdminAdminAttendeesUserIdIndexRoute:
      AuthenticatedAdminAdminAttendeesUserIdIndexRoute,
    AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute:
      AuthenticatedAdminAdminAttendeesUserIdDeliverablesKeyRoute,
  }

const AuthenticatedAdminAdminAttendeesRouteWithChildren =
  AuthenticatedAdminAdminAttendeesRoute._addFileChildren(
    AuthenticatedAdminAdminAttendeesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAttendeesRoute: typeof AuthenticatedAdminAdminAttendeesRouteWithChildren
  AuthenticatedAdminAdminRegistrationsRoute: typeof AuthenticatedAdminAdminRegistrationsRoute
  AuthenticatedAdminAdminReviewRoute: typeof AuthenticatedAdminAdminReviewRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAttendeesRoute:
    AuthenticatedAdminAdminAttendeesRouteWithChildren,
  AuthenticatedAdminAdminRegistrationsRoute:
    AuthenticatedAdminAdminRegistrationsRoute,
  AuthenticatedAdminAdminReviewRoute: AuthenticatedAdminAdminReviewRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDeliverablesRoute: typeof AuthenticatedDashboardDeliverablesRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardGoalsRoute: typeof AuthenticatedDashboardGoalsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDeliverablesRoute:
      AuthenticatedDashboardDeliverablesRoute,
    AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
    AuthenticatedDashboardGoalsRoute: AuthenticatedDashboardGoalsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
